version: '3.9'

services:

  leap_async_task:
    container_name: leap_async_task
    build:
      context: .
      dockerfile: Dockerfile
 

    volumes:
      - .:/usr/src/app

    ports:  
      - "80:8080"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - .:/redis/data
  
  worker: 
    container_name: worker
    build: 
      context: .  # Build both the Django and worker images from the same context
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
      - leap_async_task
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
    # command: ["bash", "-c", "pip install -U 'dramatiq[redis, watch]' requests  && python /app/worker.py"]