version: '3.9'

services:

  leap_async_task:
    container_name: leap_async_task
    build:
      context: .
      dockerfile: Dockerfile
 

    volumes:
      - .:/usr/src/app

    ports:  
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - .:/redis/data