# Generated by Django 5.0.3 on 2024-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
    ]
